# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5a8d56d67c67c0f1b8c1d909a956d8ff01cf1d95b25d33ff7bb0856eae0d9d589ada53d6c141cbcbfcb9c85dc48e8ccb6eb65a4e9feb744453d4742da758d477

test:
  secret_key_base: 8c1d58e59c788d99696a198782febf6a8891b011f76ffe5a6cbca78ef09d8eb44a9884ffc2848437fd8c22702aa7872e04e5b2c2e5ca62ee0ead790d5c810437

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
